### ISSUE TITLE
会存在内存泄漏问题呢。不知道是不是使用问题，帮忙分析下呢

### ISSUE THREAD

**Issue by annen6um** [GCS-ZHN/ddddocr-for-java#3]
目前是在一个定时任务类中调用这个ocrEngine
我在代码块中初始化的engine
    static {
        engine = OCREngine.instance();
        log.info("OCR引擎初始化完成");
    }
现在存在的问题是每调用一次engine.recognize(read);内存就会彪高一点，直至把内存撑爆。

为了避免是使用错误，我还特意用了第三方的验证码识别服务，替换本地ocr识别的方式，测试了几个小时，发现内存很稳定，没有问题。大佬能帮忙分析下不

**Comment by GCS-ZHN** [comment]
我下班后测试看看

**Comment by annen6um** [comment]
好的，谢谢

**Comment by GCS-ZHN** [comment]
经过进一步测试发现，似乎如果主动触发`System.gc()`，通知JVM回收对象，这样才会快速回收内存。

**Comment by annen6um** [comment]
是的，我暂时没找到具体原因，麻烦排查出原因之后发出来学习学习呗，谢谢

**Comment by ilxyil** [comment]
已解决，直接无偿公开了哈
![image](https://github.com/GCS-ZHN/ddddocr-for-java/assets/81404532/0bdb6a39-11ee-4e3e-be6c-778d4f50ccf7)

**Comment by GCS-ZHN** [comment]
已经在新的release中修复
